/*global alert, console*/
var a = 3;
var b = 5;
var c;
var newLine = "\n";
var message = "var a = 3;\nvar b = 5;\nvar c;\n-------------";
message += newLine;
message += ("a + b = " + (a + b));
message += newLine;
message += ("a + b = " + (a - b));
message += newLine;
message += ("a * b = " + (a * b));
message += newLine;
message += ("a / b = " + (a / b));
message += newLine;
message += ("a % b = " + (a % b));
message += newLine;
message += ("a += b = " + (a += b));
message += newLine;
message += ("a -= b = " + (a -= b));
message += newLine;
message += ("a *= b = " + (a *= b));
message += newLine;
message += ("a /= b = " + (a /= b));
message += newLine;
message += ("a %= b = " + (a %= b));
message += newLine;
message += ("a == b = " + (a === b));
message += newLine;
message += ("a != b = " + (a !== b));
message += newLine;
message += ("a > b = " + (a > b));
message += newLine;
message += ("a < b = " + (a < b));
message += newLine;
message += ("!a && !c = " + (!a && !c));
message += newLine;
message += ("!a || !c = " + (!a || !c));
alert(message);

var f_name = 'vikrant';
var l_name = 'chib';
var email = 'vikr0003@algonquinlive.com';
var output = "My name is " + f_name + l_name + ". You can contact me at " + email + ".";
alert(output);
